CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- Tenants (multi-tenant root)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  brand_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  smtp_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  sms_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  support_email TEXT,
  support_phone TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id),
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'base',
  name TEXT,
  api_token TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at TIMESTAMPTZ,
  UNIQUE (tenant_id, email)
);

CREATE INDEX IF NOT EXISTS users_tenant_id_idx ON users (tenant_id);

-- ---------------------------------------------------------------------------
-- Service tickets
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id),
  ticket_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 25001),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT,
  customer_phone_normalized TEXT,
  preferred_contact_channel TEXT,
  device_type TEXT NOT NULL,
  device_model TEXT,
  issue_description TEXT NOT NULL,
  additional_notes TEXT,
  disclaimer_language TEXT DEFAULT 'sv',
  status TEXT DEFAULT 'Nytt',
  user_id TEXT,
  cost_proposal_approved BOOLEAN NOT NULL DEFAULT FALSE,
  internal_notes TEXT,
  work_done_summary TEXT,
  final_cost TEXT,
  diagnosis TEXT,
  has_new_customer_message BOOLEAN NOT NULL DEFAULT FALSE,
  diagnosis_fee TEXT,
  planned_actions TEXT,
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  customer_notified_at TIMESTAMPTZ,
  picked_up_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  last_customer_response_text TEXT,
  last_customer_response_at TIMESTAMPTZ,
  last_customer_response_channel TEXT,
  last_customer_decision TEXT,
  last_staff_contact_at TIMESTAMPTZ,
  last_staff_contact_by TEXT,
  last_staff_contact_channel TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS service_tickets_ticket_number_idx ON service_tickets (ticket_number);
CREATE INDEX IF NOT EXISTS service_tickets_phone_norm_idx ON service_tickets (customer_phone_normalized);
CREATE INDEX IF NOT EXISTS service_tickets_tenant_id_idx ON service_tickets (tenant_id);

-- ---------------------------------------------------------------------------
-- Message logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS message_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id),
  ticket_id UUID REFERENCES service_tickets(id) ON DELETE SET NULL,
  channel TEXT NOT NULL,
  direction TEXT NOT NULL,
  sender_user TEXT,
  to_number TEXT,
  from_number TEXT,
  subject TEXT,
  body TEXT,
  raw_body TEXT,
  parse_method TEXT,
  parse_confidence TEXT,
  message_id TEXT,
  in_reply_to TEXT,
  references_header TEXT,
  reply_token TEXT,
  provider TEXT,
  provider_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS message_logs_ticket_id_idx ON message_logs (ticket_id);
CREATE INDEX IF NOT EXISTS message_logs_channel_direction_idx ON message_logs (channel, direction);
CREATE INDEX IF NOT EXISTS message_logs_provider_id_idx ON message_logs (provider, provider_id) WHERE provider_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS message_logs_created_at_idx ON message_logs (created_at);
CREATE INDEX IF NOT EXISTS message_logs_tenant_id_idx ON message_logs (tenant_id);

-- ---------------------------------------------------------------------------
-- App settings (per tenant)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_settings (
  tenant_id UUID NOT NULL REFERENCES tenants(id),
  key TEXT NOT NULL,
  value_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (tenant_id, key)
);

-- ---------------------------------------------------------------------------
-- Translation cache (shared across tenants)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS translation_cache (
  source_text TEXT NOT NULL,
  target_language TEXT NOT NULL,
  translated_text TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (source_text, target_language)
);
